# Central declaration of dependencies (Gradle Version Catalog)
# https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml

# Declaring Rich and/or Ranged Versions
# https://docs.gradle.org/current/userguide/rich_versions.html
# https://docs.gradle.org/current/userguide/single_versions.html


[versions]

fluxoKmpConf = "0.1.0"

# Java/Kotlin compatibility
javaLangTarget = "11"
kotlinLangVersion = "1.5"
kotlinCoreLibraries = "1.5.32"

# Kotlin version, aligned with Compose Multiplatform
# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-gradle-plugin
# https://github.com/JetBrains/kotlin/releases
kotlin = "1.8.22"

# Compose Multiplatform from JetBrains
# https://github.com/JetBrains/compose-multiplatform/releases
jetbrains-compose = "1.4.0"

# https://github.com/google/ksp/releases
ksp = "1.8.20-1.0.11"

# https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google
android-gradle-plugin = "8.0.2"

# Public API management tool
# https://github.com/Kotlin/binary-compatibility-validator/releases
# 0.13+ uses Kotlin metadata 0.6.0 (conflicts with AtomicFU!)
bcv = "0.12.1"

# Dokka is a documentation engine for Kotlin/Java
# https://github.com/Kotlin/dokka/releases
# https://mvnrepository.com/artifact/org.jetbrains.dokka/dokka-gradle-plugin?repo=space-kotlin-dokka-dev
dokka = "1.8.10"

# https://github.com/detekt/detekt/releases
detekt = "1.23.0"

# https://github.com/pinterest/ktlint/releases
ktlint = "0.49.1"

# https://plugins.gradle.org/plugin/com.diffplug.gradle.spotless
spotless = "6.19.0"

# Gradle plugin for building plugins for IntelliJ-based IDEs
# https://plugins.gradle.org/plugin/org.jetbrains.intellij
# https://github.com/JetBrains/gradle-intellij-plugin/releases
gradle-intellij-plugin = "1.14.0"


[libraries]

ktlint = { module = "com.pinterest:ktlint", version.ref = "ktlint" }

detekt-core = { module = "io.gitlab.arturbosch.detekt:detekt-core", version.ref = "detekt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

plugin-android = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
plugin-binCompatValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "bcv" }
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
plugin-intellij = { module = "org.jetbrains.intellij.plugins:gradle-intellij-plugin", version.ref = "gradle-intellij-plugin" }
plugin-jetbrains-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "jetbrains-compose" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-ksp = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }
plugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }


[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-sam-receiver = { id = "org.jetbrains.kotlin.plugin.sam.with.receiver", version.ref = "kotlin" }
kotlinx-binCompatValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "bcv" }

detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

# Publish plugins to the Gradle Plugin Portal
# https://plugins.gradle.org/plugin/com.gradle.plugin-publish
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version = "1.2.0" }

# Build scans, data to speed up build and improve build reliability.
# https://scans.gradle.com/plugin/
# https://plugins.gradle.org/plugin/com.gradle.enterprise
gradle-enterprise = { id = "com.gradle.enterprise", version = "3.13.3" }

# Gradle Versions Plugin: provides a task to determine which dependencies have updates
# https://github.com/ben-manes/gradle-versions-plugin/releases
# https://plugins.gradle.org/plugin/com.github.ben-manes.versions
deps-versions = { id = "com.github.ben-manes.versions", version = "0.47.0" }

# Detect unused and misused dependencies. Provides advice for managing dependencies and other applied plugins.
# https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/CHANGELOG.md
# https://plugins.gradle.org/plugin/com.autonomousapps.dependency-analysis
# https://mvnrepository.com/artifact/com.autonomousapps/dependency-analysis-gradle-plugin
deps-analysis = { id = "com.autonomousapps.dependency-analysis", version = "1.20.0" }

# Plugin that guards against unintentional dependency changes
# https://github.com/dropbox/dependency-guard/blob/main/CHANGELOG.md#change-log
# https://mvnrepository.com/artifact/com.dropbox.dependency-guard/dependency-guard
deps-guard = { id = "com.dropbox.dependency-guard", version = "0.4.3" }

# `taskTree` task that prints the current task graph
# https://github.com/dorongold/gradle-task-tree/blob/master/CHANGELOG.md#changelog
# https://plugins.gradle.org/plugin/com.dorongold.task-tree
task-tree = { id = "com.dorongold.task-tree", version = "2.1.1" }

# Provides task metadata and dependency information, execution queue, and more
# https://gitlab.com/barfuin/gradle-taskinfo/-/tags
# https://plugins.gradle.org/plugin/org.barfuin.gradle.taskinfo
task-info = { id = "org.barfuin.gradle.taskinfo", version = "2.1.0" }

# `graphModules` task to create an image with the graph of how gradle modules depend on each other
# https://github.com/savvasdalkitsis/module-dependency-graph/releases
# https://plugins.gradle.org/plugin/com.savvasdalkitsis.module-dependency-graph
module-dependency-graph = { id = "com.savvasdalkitsis.module-dependency-graph", version = "0.12" }

# Generating BuildConstants for any kind of project
# https://github.com/gmazzo/gradle-buildconfig-plugin
# https://plugins.gradle.org/plugin/com.github.gmazzo.buildconfig
build-config = { id = "com.github.gmazzo.buildconfig", version = "4.0.4" }

# Resolve all dependencies used in a gradle module, with associated license and further information.
# https://github.com/mikepenz/AboutLibraries
# https://plugins.gradle.org/plugin/com.mikepenz.aboutlibraries.plugin
about-libraries = { id = "com.mikepenz.aboutlibraries.plugin", version = "10.7.0" }
