
# ProGuard/R8 keep rules
# Auto-generated by Fluxo task :generateShrinkerKeepRulesFromApi from API reports:
# - api\check-gradle-plugin.api
# DO NOT EDIT MANUALLY!

-keep,allowoptimization public final class NewPlugin {
    public <init>();
    public synthetic void apply(java.lang.Object);
    public void apply(org.gradle.api.Project);
}

