# https://detekt.github.io/detekt/configurations.html
# https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml
# https://github.com/detekt/detekt/blob/main/detekt-formatting/src/main/resources/config/config.yml

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false

output-reports:
  active: true
  exclude:
    - 'TxtOutputReport'
    - 'XmlOutputReport'
    - 'HtmlOutputReport'
    - 'MdOutputReport'

console-reports:
  active: true
  exclude: [ ]

exceptions:
  TooGenericExceptionCaught:
    active: false

complexity:
  LongParameterList:
    ignoreDefaultParameters: true
  TooManyFunctions:
    ignoreDeprecated: true
    ignoreOverridden: true
    ignoreAnnotatedFunctions: ['Preview']

style:
  LoopWithTooManyJumpStatements:
    maxJumpCount: 2
  MaxLineLength:
    maxLineLength: 100
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']

naming:
  excludes:
    - '**/build/generated/**'
  FunctionNaming:
    ignoreAnnotated: ['Composable']
  NoNameShadowing:
    # False positives with SAM receiver usage
    active: false

formatting:
  excludes:
    - '**/fluxo/conf/data/BuildConstants.kt'
    - '**/build/generated/**'
  ArgumentListWrapping:
    maxLineLength: 100
  FunctionSignature:
    maxLineLength: 100
  MaximumLineLength:
    maxLineLength: 100
  NoConsecutiveBlankLines:
    active: false
  ParameterListWrapping:
    maxLineLength: 100
  ImportOrdering:
    active: true
    autoCorrect: true
    layout: '*'
