name: Clear cache

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443

      - name: Clear cache
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            console.log("About to clear all GitHub Actions caches")
            const owner = context.repo.owner
            const repo = context.repo.repo
            const caches = await github.rest.actions.getActionsCacheList({
              owner: owner,
              repo: repo,
            })
            for (const cache of caches.data.actions_caches) {
              await github.rest.actions.deleteActionsCacheById({
                owner: owner,
                repo: repo,
                cache_id: cache.id,
              })
              console.log(`cleaned cache "${cache.key}"`)
            }
            console.log("Clear completed")
