name: Clear cache

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        uses: actions/github-script@v7
        continue-on-error: true
        with:
          script: |
            console.log("About to clear all GitHub Actions caches")
            const owner = context.repo.owner
            const repo = context.repo.repo
            const caches = await github.rest.actions.getActionsCacheList({
              owner: owner,
              repo: repo,
            })
            for (const cache of caches.data.actions_caches) {
              await github.rest.actions.deleteActionsCacheById({
                owner: owner,
                repo: repo,
                cache_id: cache.id,
              })
              console.log(`cleaned cache "${cache.key}"`)
            }
            console.log("Clear completed")
