name: "Validate Gradle Wrapper"

on:
  pull_request:
    paths:
      - '**/gradle-wrapper-validation.yml'
      - '**/gradle/wrapper/'
      - '**/gradle-wrapper.jar'
      - '**/gradle*.properties'
      - '**/gradlew*'
  push:
    paths:
      - '**/gradle-wrapper-validation.yml'
      - '**/gradle/wrapper/'
      - '**/gradle-wrapper.jar'
      - '**/gradle*.properties'
      - '**/gradlew*'

permissions:
  contents: read

jobs:
  validation:
    name: "Validate Gradle Wrapper"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            downloads.gradle-dn.com:443
            github.com:443
            services.gradle.org:443
            downloads.gradle.org:443
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
