name: Validate Gradle Wrapper

on:
  pull_request:
    paths:
      - '**/gradle-wrapper-validation.yml'
      - '**/gradle/wrapper/'
      - '**/gradle-wrapper.jar'
      - '**/gradle*.properties'
      - '**/gradlew*'
  push:
    paths:
      - '**/gradle-wrapper-validation.yml'
      - '**/gradle/wrapper/'
      - '**/gradle-wrapper.jar'
      - '**/gradle*.properties'
      - '**/gradlew*'

permissions:
  contents: read

jobs:
  validation:
    name: "Validate Gradle Wrapper"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            downloads.gradle-dn.com:443
            downloads.gradle.org:443
            services.gradle.org:443

      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
