name: Validate Gradle Wrapper

on:
  pull_request:
    paths:
      - '**/gradle-wrapper-validation.yml'
      - '**/gradle/wrapper/'
      - '**/gradle-wrapper.jar'
      - '**/gradle*.properties'
      - '**/gradlew*'
  push:
    branches:
      - main
      - dev
    paths:
      - '**/gradle-wrapper-validation.yml'
      - '**/gradle/wrapper/'
      - '**/gradle-wrapper.jar'
      - '**/gradle*.properties'
      - '**/gradlew*'

permissions:
  contents: read

jobs:
  validation:
    name: "Validate Gradle Wrapper"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@351661ca32ac09a36dc5ee2d536e3128f2a3c8ed # v2.22.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            downloads.gradle.org:443
            services.gradle.org:443

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: gradle/actions/wrapper-validation@3f5f9adaf7d9fecd50b5935e54106014257a94e6 # v6.4.0
